# Generated by Django 4.2.6 on 2023-10-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('first_name', models.CharField(max_length=50)),
                ('availability', models.BooleanField(default=True, verbose_name='azyrky uchurda ishteyt')),
                ('image', models.ImageField(blank=True, upload_to='p/%Y/%m/%d')),
                ('position', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
    ]
