# Generated by Django 4.2.6 on 2023-10-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('name',), 'verbose_name': 'menu', 'verbose_name_plural': 'menus'},
        ),
    ]
