# Generated by Django 4.2.6 on 2023-10-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_menu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
