# Generated by Django 4.2.6 on 2023-10-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_employee_phone_employee_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Restauran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d')),
            ],
        ),
    ]
