# Generated by Django 4.2.6 on 2023-10-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_restaura_restauran_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaura',
            name='image',
            field=models.ImageField(blank=True, upload_to='img/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='restauran',
            name='image',
            field=models.ImageField(blank=True, upload_to='im/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to='i/%Y/%m/%d'),
        ),
    ]
