# Generated by Django 4.2.6 on 2023-10-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_restaura_image_alter_restauran_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='new_dishes/%Y/%m/%d')),
            ],
        ),
    ]
